### ISSUE TITLE
Can you open source your model after textual SFT or multi-modal SFT?

### ISSUE THREAD

**Issue by Polly-LYP** [AI45Lab/VLSBench#2]
Hello. I'm really interested in your great work! Can you open source your your model after textual SFT or multi-modal SFT?

**Comment by hxhcreate** [comment]
Thanks for your question.

The organization of the training set, training code, and model checkpoints is heavy work for us as we strive for the next work.  Thus, We do not have an immediate plan to release them all. However, we will release it immediately when we organize these things well.

We appreciate your attention to our work. If you have any more questions, please feel free to email me.

**Comment by hxhcreate** [comment]
Check the latest update, thanks
